# Generated by Django 3.0 on 2022-08-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220810_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advuser',
            old_name='send_message',
            new_name='send_messages',
        ),
    ]
